//! Writes `web/icons.js` from `vellum_ui::icon`, so the browser draws the Mac's icons.
//!
//! ```text
//! cargo run -p vellum-ui --example web-icons > web/icons.js
//! ```
//!
//! # Why this exists
//!
//! `web/tools.js`, `web/chrome.js` and `web/find.js` each hand-wrote their own SVG paths —
//! three separate copies of a table `crates/vellum-ui/src/icon.rs` had already drawn once, and
//! that module's header records what drawing an icon by hand actually costs: the **hand** took
//! three attempts and every one had to be screenshotted before anybody could see it read as a
//! smudge at 24pt. The organic ones there are converted from Lucide by `scripts/icons.py`
//! rather than drawn at all.
//!
//! So the browser was carrying the expensive part twice and getting a different answer. This
//! walks the real table and emits it, which makes the Mac the single source and a redraw
//! there something the tab picks up by re-running one command.
//!
//! # What comes out
//!
//! ```js
//! export const ICONS = {
//!   select: [{ d: 'M…', fill: true }],
//!   …
//! };
//! ```
//!
//! A **list of subpaths**, not one string, because the table holds three kinds of thing the
//! old hand-written paths could not: a filled contour, a stroked one, and a circle. A single
//! `d` with one `stroke` attribute cannot say that a pointer is solid and a shape's circle is
//! not. `web/icons.js`'s own `svg()` renders the list.
//!
//! # The grid
//!
//! [`GRID`] units square, to match what the page already draws into, with the geometry scaled
//! from the unit box `icon.rs` holds. A circle is scaled by the grid too rather than by a
//! side, which is the same rule `Icon::paint` applies — on a square box the two agree exactly.

use std::fmt::Write as _;

use vellum_ui::icon::{Icon, Prim};

/// The box the page draws into. `web/tools.js`'s existing `viewBox="0 0 20 20"`, kept so the
/// generated table drops in beside the CSS that was already sizing those icons.
const GRID: f32 = 20.0;

/// Decimal places in the output. Three is a thousandth of an icon — far below a device pixel
/// at any size these are drawn at, and it keeps the file readable.
const PLACES: usize = 3;

/// Every icon the page asks for, under the name the page asks for it by.
///
/// ⚠ **The web's names, not the Rust ones**, and that is deliberate: this file is the one
/// place the two vocabularies meet. A rename on either side is a compile error or a missing
/// key here rather than an icon that silently stops being drawn.
///
/// `more` is the one entry with no counterpart. The Mac draws *More* as a vertical `⋮`,
/// which is what the selection bar wants; the palette wants the same three marks lying down.
/// It is generated by rotating them rather than by drawing a second row of dots, so the two
/// cannot drift.
const WANTED: &[(&str, Icon)] = &[
    // The palette.
    ("select", Icon::Select),
    ("hand", Icon::Hand),
    ("sticky", Icon::Sticky),
    ("text", Icon::Text),
    ("shape", Icon::Shape),
    ("frame", Icon::Frame),
    ("pen", Icon::Pen),
    ("eraser", Icon::Eraser),
    ("connector", Icon::Connector),
    ("moreVertical", Icon::More),
    // The selection bar and the menus.
    ("undo", Icon::Undo),
    ("redo", Icon::Redo),
    ("lock", Icon::Lock),
    ("unlock", Icon::Unlock),
    ("opacity", Icon::Opacity),
    ("strokeWidth", Icon::Thickness),
    ("trash", Icon::Trash),
    ("duplicate", Icon::Duplicate),
    // The top bar.
    ("back", Icon::ChevronLeft),
    ("minus", Icon::ZoomOut),
    ("plus", Icon::ZoomIn),
    ("fit", Icon::ZoomToFit),
    // Find.
    ("find", Icon::Search),
    ("prev", Icon::ChevronUp),
    ("next", Icon::ChevronDown),
    ("close", Icon::Close),
    // The properties panel.
    ("textAlignLeft", Icon::TextAlignLeft),
    ("textAlignCenter", Icon::TextAlignCenter),
    ("textAlignRight", Icon::TextAlignRight),
    // The rest of *More*, so a later row can draw itself.
    ("image", Icon::Image),
    ("table", Icon::Table),
    ("chart", Icon::Chart),
    ("mindmap", Icon::MindMap),
    ("kanban", Icon::Kanban),
];

fn main() {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("export const ICONS = {\n");
    for (name, icon) in WANTED {
        writeln!(out, "  {name}: {},", subpaths(icon.prims())).expect("writing to a String");
    }
    // See `WANTED`: the same three marks, turned a quarter turn. `Icon::More` is already
    // the vertical `⋮` the selection bar wants, so it is the *palette's* horizontal `⋯` that
    // is generated — the rotation runs this way round and not the other.
    let turned: Vec<Prim> = Icon::More.prims().iter().map(|prim| rotated(*prim)).collect();
    writeln!(out, "  more: {},", subpaths(&turned)).expect("writing to a String");
    out.push_str("};\n");
    print!("{out}");
}

/// One icon's prims as a JS array of `{ d, fill }`.
fn subpaths(prims: &[Prim]) -> String {
    let mut parts = Vec::new();
    for prim in prims {
        match *prim {
            Prim::Poly { pts, closed, fill } => {
                if pts.is_empty() {
                    continue;
                }
                let mut d = String::new();
                for (index, point) in pts.iter().enumerate() {
                    let (x, y) = scaled(*point);
                    let verb = if index == 0 { 'M' } else { 'L' };
                    write!(d, "{verb}{x} {y}").expect("writing to a String");
                    if index + 1 < pts.len() {
                        d.push(' ');
                    }
                }
                // A filled contour is closed by definition; an outline is closed when the
                // table says so. `Z` and not a repeated first point, so the join at the seam
                // is a join rather than two ends meeting.
                if closed || fill {
                    d.push('Z');
                }
                parts.push(format!("{{ d: '{d}', fill: {fill} }}"));
            }
            // ⚠ Two half arcs, not one. An SVG arc whose start and end are the same point
            // draws nothing at all, so a full circle cannot be a single `A`.
            Prim::Circle { c, r, fill } => {
                let (cx, cy) = (c.0 * GRID, c.1 * GRID);
                let radius = r * GRID;
                let (left, right) = (round(cx - radius), round(cx + radius));
                let (cy, radius) = (round(cy), round(radius));
                let d = format!(
                    "M{left} {cy}A{radius} {radius} 0 1 0 {right} {cy}\
                     A{radius} {radius} 0 1 0 {left} {cy}Z"
                );
                parts.push(format!("{{ d: '{d}', fill: {fill} }}"));
            }
        }
    }
    format!("[{}]", parts.join(", "))
}

/// A prim turned a quarter turn clockwise about the middle of the unit box.
fn rotated(prim: Prim) -> Prim {
    // `Prim` holds `&'static [(f32, f32)]`, so the turned points have to be leaked to keep
    // that lifetime. This is a generator that runs once and exits; a `Box::leak` here costs
    // the process nothing and keeps the type the same as every other prim's.
    match prim {
        Prim::Poly { pts, closed, fill } => {
            let turned: Vec<(f32, f32)> =
                pts.iter().map(|(x, y)| (1.0 - *y, *x)).collect();
            Prim::Poly { pts: Box::leak(turned.into_boxed_slice()), closed, fill }
        }
        Prim::Circle { c, r, fill } => Prim::Circle { c: (1.0 - c.1, c.0), r, fill },
    }
}

/// A unit-box point on the [`GRID`], rounded.
fn scaled((x, y): (f32, f32)) -> (String, String) {
    (round(x * GRID), round(y * GRID))
}

/// A number with trailing zeros and a trailing point taken off, so `10.000` prints as `10`.
fn round(value: f32) -> String {
    let mut text = format!("{value:.PLACES$}");
    if text.contains('.') {
        text = text.trim_end_matches('0').trim_end_matches('.').to_owned();
    }
    // `-0` is a real output of the format above and reads as a mistake in a path.
    if text == "-0" { "0".to_owned() } else { text }
}

const HEADER: &str = "\
// The icon set, generated. **Do not edit this file.**
//
//     cargo run -p vellum-ui --example web-icons > web/icons.js
//
// The geometry is `crates/vellum-ui/src/icon.rs` — the same table the Mac paints — so a tool
// in a tab and the same tool on the Mac are the same drawing. Before this file existed,
// `tools.js`, `chrome.js` and `find.js` each hand-wrote their own paths and the three
// disagreed. `icon.rs`'s header says what drawing one by hand costs and why the organic ones
// are converted from Lucide (ISC) rather than drawn at all; that notice travels with this
// geometry.
//
// Each icon is a **list of subpaths**, because the table holds three kinds of thing a single
// stroked path cannot say: a filled contour, a stroked one, and a circle.

/// The box the geometry is scaled into, matching the `viewBox` `svg()` writes.
export const ICON_GRID = 20;

/**
 * One icon as inline SVG.
 *
 * `aria-hidden`, because every button that holds one carries an `aria-label` — a screen
 * reader announcing both would say the name twice.
 *
 * ⚠ **`round` joins and caps.** `icon.rs` draws on Lucide's 24-grid model, which is round
 * on both, and a `square` cap on a three-point polyline is what turned the old hand-written
 * dots into dashes. Accepts a legacy `d` string as well as a list, so a caller that has not
 * been converted yet still draws.
 */
export function svg(icon, grid = ICON_GRID) {
  const subpaths = typeof icon === 'string' ? [{ d: icon, fill: false }] : (icon || []);
  const body = subpaths.map(({ d, fill }) => (fill
    ? `<path d=\"${d}\" fill=\"currentColor\"/>`
    : `<path d=\"${d}\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"`
      + ' stroke-linecap=\"round\" stroke-linejoin=\"round\"/>')).join('');
  // ⚠ `width`/`height` as well as the viewBox. Three of the four callers size their icons
  // in CSS and one does not, and an SVG with no intrinsic size falls back to 300x150.
  return `<svg viewBox=\"0 0 ${grid} ${grid}\" width=\"20\" height=\"20\"`
    + ` aria-hidden=\"true\" focusable=\"false\">${body}</svg>`;
}

";
