#!/usr/bin/env python3
"""Regenerate `docs/images/palette.svg` — the swatch card in the README.

The values here are the ones in `docs/05-design-language.md` §1 and in
`vellum-ui/src/theme.rs`. Those two are joined by a test; this file is a third copy
and nothing can check it, so **if you move a token, move it here too**.

    python3 scripts/palette-svg.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

ROWS = [
    ("Accents", [
        ("signal-teal",  "#00A38C", "selection, active tool"),
        ("monitor-cyan", "#6FD6E6", "snap guides, hover"),
        ("xr-red",       "#E65B58", "destructive only"),
        ("cobalt",       "#1B62E8", "optional accent"),
    ]),
    ("Surfaces", [
        ("bone",  "#FCFDFE", "panels, menus"),
        ("milk",  "#F7F9FA", "app background"),
        ("paper", "#F5F7F8", "the board"),
        ("pearl", "#EBEEF0", "raised chrome"),
        ("frost", "#E5EAED", "borders, wells"),
    ]),
    ("Ink", [
        ("ink",       "#1A1D1F", "primary text"),
        ("ink-muted", "#5C656B", "labels"),
        ("ink-faint", "#8B959B", "placeholders"),
    ]),
]

W, SW, SH, GAP, PAD = 760, 128, 58, 12, 26
BLOCK = 22 + SH + 18 + 16 + 14 + 18          # heading, swatch, name, hex, role, gap
H = PAD * 2 + BLOCK * len(ROWS)

out = [
    "<!-- Velm's palette, generated by scripts/palette-svg.py from docs/05-design-language.md §1.",
    "     Drawn on its own light card so the near-white surfaces read on a dark README too. -->",
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}"',
    "     font-family=\"Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif\">",
    f'  <rect x="0.5" y="0.5" width="{W - 1}" height="{H - 1}" rx="14" fill="#FCFDFE" stroke="#E5EAED"/>',
]

y = PAD
for heading, swatches in ROWS:
    out.append(f'  <text x="{PAD}" y="{y + 13}" font-size="11" font-weight="700" '
               f'letter-spacing="0.08em" fill="#8B959B">{heading.upper()}</text>')
    sy = y + 22
    for i, (name, hexv, role) in enumerate(swatches):
        x = PAD + i * (SW + GAP)
        # Every swatch gets a hairline. Without it the five surfaces — only 4% apart in
        # luminance, which is the whole point of the ramp — have no edge at all on the
        # near-white card behind them.
        out.append(f'  <rect x="{x + 0.5}" y="{sy + 0.5}" width="{SW - 1}" height="{SH - 1}" '
                   f'rx="8" fill="{hexv}" stroke="#E5EAED"/>')
        out.append(f'  <text x="{x}" y="{sy + SH + 18}" font-size="13" font-weight="600" '
                   f'fill="#1A1D1F">{name}</text>')
        out.append(f'  <text x="{x}" y="{sy + SH + 34}" font-size="12" '
                   f'font-family="ui-monospace, SFMono-Regular, Menlo, monospace" '
                   f'fill="#5C656B">{hexv}</text>')
        out.append(f'  <text x="{x}" y="{sy + SH + 49}" font-size="11" fill="#8B959B">{role}</text>')
    y += BLOCK

out.append("</svg>")

target = ROOT / "docs/images/palette.svg"
target.write_text("\n".join(out) + "\n")
print(f"wrote {target.relative_to(ROOT)} — {W}x{H}")
