// The icon set, generated. **Do not edit this file.**
//
//     cargo run -p vellum-ui --example web-icons > web/icons.js
//
// The geometry is `crates/vellum-ui/src/icon.rs` — the same table the Mac paints — so a tool
// in a tab and the same tool on the Mac are the same drawing. Before this file existed,
// `tools.js`, `chrome.js` and `find.js` each hand-wrote their own paths and the three
// disagreed. `icon.rs`'s header says what drawing one by hand costs and why the organic ones
// are converted from Lucide (ISC) rather than drawn at all; that notice travels with this
// geometry.
//
// Each icon is a **list of subpaths**, because the table holds three kinds of thing a single
// stroked path cannot say: a filled contour, a stroked one, and a circle.

/// The box the geometry is scaled into, matching the `viewBox` `svg()` writes.
export const ICON_GRID = 20;

/**
 * One icon as inline SVG.
 *
 * `aria-hidden`, because every button that holds one carries an `aria-label` — a screen
 * reader announcing both would say the name twice.
 *
 * ⚠ **`round` joins and caps.** `icon.rs` draws on Lucide's 24-grid model, which is round
 * on both, and a `square` cap on a three-point polyline is what turned the old hand-written
 * dots into dashes. Accepts a legacy `d` string as well as a list, so a caller that has not
 * been converted yet still draws.
 */
export function svg(icon, grid = ICON_GRID) {
  const subpaths = typeof icon === 'string' ? [{ d: icon, fill: false }] : (icon || []);
  const body = subpaths.map(({ d, fill }) => (fill
    ? `<path d="${d}" fill="currentColor"/>`
    : `<path d="${d}" fill="none" stroke="currentColor" stroke-width="1.5"`
      + ' stroke-linecap="round" stroke-linejoin="round"/>')).join('');
  // ⚠ `width`/`height` as well as the viewBox. Three of the four callers size their icons
  // in CSS and one does not, and an SVG with no intrinsic size falls back to 300x150.
  return `<svg viewBox="0 0 ${grid} ${grid}" width="20" height="20"`
    + ` aria-hidden="true" focusable="false">${body}</svg>`;
}

export const ICONS = {
  select: [{ d: 'M3.36 3.9 L3.36 3.58 L3.58 3.36 L3.9 3.36 L17.24 8.78 L17.48 9.02 L17.46 9.36 L17.18 9.56 L12.08 10.88 L11.68 11.06 L11.32 11.32 L11.06 11.68 L10.88 12.08 L9.56 17.18 L9.36 17.46 L9.02 17.48 L8.78 17.24Z', fill: false }],
  hand: [{ d: 'M15 9.16 L15 5 L14.94 4.56 L14.78 4.16 L14.52 3.82 L14.16 3.56 L13.76 3.4 L13.34 3.34 L12.9 3.4 L12.5 3.56 L12.16 3.82 L11.88 4.16 L11.72 4.56 L11.66 5', fill: false }, { d: 'M11.66 8.34 L11.66 3.34 L11.6 2.9 L11.44 2.5 L11.18 2.16 L10.84 1.88 L10.44 1.72 L10 1.66 L9.56 1.72 L9.16 1.88 L8.82 2.16 L8.56 2.5 L8.4 2.9 L8.34 3.34 L8.34 5', fill: false }, { d: 'M8.34 8.76 L8.34 5 L8.28 4.56 L8.12 4.16 L7.84 3.82 L7.5 3.56 L7.1 3.4 L6.66 3.34 L6.24 3.4 L5.84 3.56 L5.48 3.82 L5.22 4.16 L5.06 4.56 L5 5 L5 11.66', fill: false }, { d: 'M15 6.66 L15.08 6.16 L15.32 5.68 L15.68 5.32 L16.16 5.08 L16.66 5 L17.18 5.08 L17.64 5.32 L18.02 5.68 L18.26 6.16 L18.34 6.66 L18.34 11.66 L18.3 12.24 L18.24 12.82 L18.1 13.4 L17.94 13.94 L17.7 14.48 L17.44 15 L17.12 15.5 L16.78 15.96 L16.38 16.38 L15.96 16.78 L15.5 17.12 L15 17.44 L14.48 17.7 L13.94 17.94 L13.4 18.1 L12.82 18.24 L12.24 18.3 L11.66 18.34 L10 18.34 L9.54 18.32 L9.12 18.3 L8.7 18.24 L8.32 18.18 L7.94 18.1 L7.6 18 L7.26 17.88 L6.94 17.76 L6.62 17.6 L6.34 17.44 L6.06 17.26 L5.78 17.06 L5.52 16.84 L5.26 16.62 L5 16.38 L2 13.38 L1.74 12.96 L1.6 12.48 L1.6 11.98 L1.76 11.5 L2.06 11.08 L2.48 10.78 L2.96 10.62 L3.46 10.62 L3.94 10.76 L4.36 11.04 L5.84 12.5', fill: false }],
  sticky: [{ d: 'M3.6 3.6 L16.4 3.6 L16.4 12 L12 16.4 L3.6 16.4Z', fill: false }, { d: 'M16.4 12 L12 12 L12 16.4', fill: false }],
  text: [{ d: 'M4.8 6.4 L4.8 4.4 L15.2 4.4 L15.2 6.4', fill: false }, { d: 'M10 4.4 L10 15.6', fill: false }, { d: 'M7.6 15.6 L12.4 15.6', fill: false }],
  shape: [{ d: 'M2.8 6.4 L11.2 6.4 L11.2 14.8 L2.8 14.8Z', fill: false }, { d: 'M8.4 8.4A4.8 4.8 0 1 0 18 8.4A4.8 4.8 0 1 0 8.4 8.4Z', fill: false }],
  frame: [{ d: 'M18.34 5 L1.66 5', fill: false }, { d: 'M18.34 15 L1.66 15', fill: false }, { d: 'M5 1.66 L5 18.34', fill: false }, { d: 'M15 1.66 L15 18.34', fill: false }],
  pen: [{ d: 'M17.64 5.68 L18 5.24 L18.22 4.72 L18.32 4.16 L18.3 3.6 L18.12 3.06 L17.84 2.56 L17.44 2.16 L16.94 1.88 L16.4 1.7 L15.84 1.68 L15.28 1.78 L14.76 2 L14.32 2.36 L3.2 13.48 L3.02 13.68 L2.88 13.92 L2.78 14.16 L1.68 17.8 L1.7 18.08 L1.92 18.3 L2.2 18.32 L5.84 17.22 L6.08 17.12 L6.32 16.98 L6.52 16.8Z', fill: false }, { d: 'M12.5 4.16 L15.84 7.5', fill: false }],
  eraser: [{ d: 'M4.8 12 L10.8 4.4 L15.6 8.4 L9.6 16Z', fill: false }, { d: 'M4 16.8 L16.8 16.8', fill: false }],
  connector: [{ d: 'M6 14 L14 6', fill: false }, { d: 'M2.8 15.2A2 2 0 1 0 6.8 15.2A2 2 0 1 0 2.8 15.2Z', fill: false }, { d: 'M13.2 4.8A2 2 0 1 0 17.2 4.8A2 2 0 1 0 13.2 4.8Z', fill: false }],
  moreVertical: [{ d: 'M8.4 4A1.6 1.6 0 1 0 11.6 4A1.6 1.6 0 1 0 8.4 4Z', fill: true }, { d: 'M8.4 10A1.6 1.6 0 1 0 11.6 10A1.6 1.6 0 1 0 8.4 10Z', fill: true }, { d: 'M8.4 16A1.6 1.6 0 1 0 11.6 16A1.6 1.6 0 1 0 8.4 16Z', fill: true }],
  undo: [{ d: 'M16 16 L14.8 11.6 L11.6 8.8 L7.2 7.6 L4.4 7.6', fill: false }, { d: 'M7.6 4.8 L4 7.6 L7.6 10.4', fill: false }],
  redo: [{ d: 'M4 16 L5.2 11.6 L8.4 8.8 L12.8 7.6 L15.6 7.6', fill: false }, { d: 'M12.4 4.8 L16 7.6 L12.4 10.4', fill: false }],
  lock: [{ d: 'M5.2 9.2 L14.8 9.2 L14.8 16.8 L5.2 16.8Z', fill: false }, { d: 'M7.2 9.2 L7.2 6.2 L8.2 4.2 L10 3.6 L11.8 4.2 L12.8 6.2 L12.8 9.2', fill: false }],
  unlock: [{ d: 'M5.2 9.2 L14.8 9.2 L14.8 16.8 L5.2 16.8Z', fill: false }, { d: 'M7.2 9.2 L7.2 6.2 L8.2 4.2 L10 3.6 L11.8 4.2 L12.6 6', fill: false }],
  opacity: [{ d: 'M2.8 10A7.2 7.2 0 1 0 17.2 10A7.2 7.2 0 1 0 2.8 10Z', fill: false }, { d: 'M10 2.8 L10 17.2', fill: false }, { d: 'M10 6.4 L13.6 6.4', fill: false }, { d: 'M10 10 L17.2 10', fill: false }, { d: 'M10 13.6 L13.6 13.6', fill: false }],
  strokeWidth: [{ d: 'M3.2 5.6 L16.8 5.6', fill: false }, { d: 'M3.2 10 L16.8 10', fill: false }, { d: 'M3.2 10.8 L16.8 10.8', fill: false }, { d: 'M3.2 14.8 L16.8 14.8', fill: false }, { d: 'M3.2 16 L16.8 16', fill: false }, { d: 'M3.2 17.2 L16.8 17.2', fill: false }],
  trash: [{ d: 'M3.2 5.2 L16.8 5.2', fill: false }, { d: 'M8 5.2 L8 3.2 L12 3.2 L12 5.2', fill: false }, { d: 'M4.8 5.2 L5.8 17.2 L14.2 17.2 L15.2 5.2', fill: false }],
  duplicate: [{ d: 'M2.8 2.8 L12 2.8 L12 12 L2.8 12Z', fill: false }, { d: 'M8 8 L17.2 8 L17.2 17.2 L8 17.2Z', fill: false }],
  back: [{ d: 'M12 6 L8 10 L12 14', fill: false }],
  minus: [{ d: 'M3.6 8.8A5.2 5.2 0 1 0 14 8.8A5.2 5.2 0 1 0 3.6 8.8Z', fill: false }, { d: 'M12.6 12.6 L16.8 16.8', fill: false }, { d: 'M6.2 8.8 L11.4 8.8', fill: false }],
  plus: [{ d: 'M3.6 8.8A5.2 5.2 0 1 0 14 8.8A5.2 5.2 0 1 0 3.6 8.8Z', fill: false }, { d: 'M12.6 12.6 L16.8 16.8', fill: false }, { d: 'M6.2 8.8 L11.4 8.8', fill: false }, { d: 'M8.8 6.2 L8.8 11.4', fill: false }],
  fit: [{ d: 'M2.8 7.2 L2.8 2.8 L7.2 2.8', fill: false }, { d: 'M12.8 2.8 L17.2 2.8 L17.2 7.2', fill: false }, { d: 'M17.2 12.8 L17.2 17.2 L12.8 17.2', fill: false }, { d: 'M7.2 17.2 L2.8 17.2 L2.8 12.8', fill: false }, { d: 'M6.8 6.8 L13.2 6.8 L13.2 13.2 L6.8 13.2Z', fill: false }],
  find: [{ d: 'M3.6 8.8A5.2 5.2 0 1 0 14 8.8A5.2 5.2 0 1 0 3.6 8.8Z', fill: false }, { d: 'M12.6 12.6 L16.8 16.8', fill: false }],
  prev: [{ d: 'M6 12 L10 8 L14 12', fill: false }],
  next: [{ d: 'M6 8 L10 12 L14 8', fill: false }],
  close: [{ d: 'M5.2 5.2 L14.8 14.8', fill: false }, { d: 'M14.8 5.2 L5.2 14.8', fill: false }],
  textAlignLeft: [{ d: 'M3.2 4.8 L16.8 4.8', fill: false }, { d: 'M3.2 8.2 L12 8.2', fill: false }, { d: 'M3.2 11.6 L16.8 11.6', fill: false }, { d: 'M3.2 15 L12 15', fill: false }],
  textAlignCenter: [{ d: 'M3.2 4.8 L16.8 4.8', fill: false }, { d: 'M5.6 8.2 L14.4 8.2', fill: false }, { d: 'M3.2 11.6 L16.8 11.6', fill: false }, { d: 'M5.6 15 L14.4 15', fill: false }],
  textAlignRight: [{ d: 'M3.2 4.8 L16.8 4.8', fill: false }, { d: 'M8 8.2 L16.8 8.2', fill: false }, { d: 'M3.2 11.6 L16.8 11.6', fill: false }, { d: 'M8 15 L16.8 15', fill: false }],
  image: [{ d: 'M3.2 4.8 L16.8 4.8 L16.8 15.2 L3.2 15.2Z', fill: false }, { d: 'M5.8 7.8A1.2 1.2 0 1 0 8.2 7.8A1.2 1.2 0 1 0 5.8 7.8Z', fill: true }, { d: 'M4 14.4 L8.4 10 L11 12.2 L13.2 10.2 L16.4 13.6', fill: false }],
  table: [{ d: 'M2.8 3.6 L17.2 3.6 L17.2 16.4 L2.8 16.4Z', fill: false }, { d: 'M2.8 7.2 L17.2 7.2', fill: false }, { d: 'M2.8 11.8 L17.2 11.8', fill: false }, { d: 'M7.6 3.6 L7.6 16.4', fill: false }, { d: 'M12.4 3.6 L12.4 16.4', fill: false }],
  chart: [{ d: 'M3.2 16.4 L16.8 16.4', fill: false }, { d: 'M5.6 16.4 L5.6 10.4', fill: false }, { d: 'M10 16.4 L10 5.6', fill: false }, { d: 'M14.4 16.4 L14.4 8.4', fill: false }],
  mindmap: [{ d: 'M1.6 8 L7.6 8 L7.6 12 L1.6 12Z', fill: false }, { d: 'M12.4 2.8 L18.4 2.8 L18.4 6.8 L12.4 6.8Z', fill: false }, { d: 'M12.4 13.2 L18.4 13.2 L18.4 17.2 L12.4 17.2Z', fill: false }, { d: 'M7.6 10 L10 10 L10 4.8 L12.4 4.8', fill: false }, { d: 'M10 10 L10 15.2 L12.4 15.2', fill: false }],
  kanban: [{ d: 'M2 3.2 L7.2 3.2 L7.2 16.8 L2 16.8Z', fill: false }, { d: 'M8.4 3.2 L13.6 3.2 L13.6 16.8 L8.4 16.8Z', fill: false }, { d: 'M14.8 3.2 L18 3.2 L18 16.8 L14.8 16.8Z', fill: false }, { d: 'M9.2 4.8 L12.8 4.8 L12.8 8 L9.2 8Z', fill: true }],
  more: [{ d: 'M14.4 10A1.6 1.6 0 1 0 17.6 10A1.6 1.6 0 1 0 14.4 10Z', fill: true }, { d: 'M8.4 10A1.6 1.6 0 1 0 11.6 10A1.6 1.6 0 1 0 8.4 10Z', fill: true }, { d: 'M2.4 10A1.6 1.6 0 1 0 5.6 10A1.6 1.6 0 1 0 2.4 10Z', fill: true }],
};
